### ISSUE TITLE
Refactor token builder helper in tests.

### ISSUE THREAD

**Issue by sqin2019** [abcxyz/jvs#142]
follow up of #112
- Refactor token builder helper in tests
- [Prerequisite task](https://github.com/abcxyz/pkg/issues/42) in abcxyz/pkg - create top-level token builder helper in the [pkg package](https://github.com/abcxyz/pkg/blob/main/testutil/jwt.go) and remove the ones not used if needed.

**Comment by yolocs** [comment]
I feel this should belong to abcxyz/pkg?

**Comment by yolocs** [comment]
Like https://github.com/abcxyz/pkg/tree/main/testutil

**Comment by sqin2019** [comment]
> Like https://github.com/abcxyz/pkg/tree/main/testutil

yes, thanks for pointing that out, it already has one https://github.com/abcxyz/pkg/blob/main/testutil/jwt.go, we might want to create a few variants to accommodate, such as, the validate cli command test(have the issue time fixed, so that we can compare the test output).

**Comment by yolocs** [comment]
The old one might not be useful anymore. If not, we can just delete it.

**Comment by sethvargo** [comment]
Do we still need this?
