### ISSUE TITLE
Update docs about jvsctl usage

### ISSUE THREAD

**Issue by yolocs** [abcxyz/jvs#188]
After this change: https://github.com/abcxyz/jvs/pull/186

**Comment by sethvargo** [comment]
What exactly do we need to update? The CLI is backwards compatible, so all of the examples should apply. I don't want to have two source of truth for docs. `jvsctl -h` should be the source of truth imo.

**Comment by sethvargo** [comment]
@yolocs do you know which docs we need to update?

**Comment by yolocs** [comment]
https://github.com/abcxyz/jvs/blob/main/docs/cli-tool.md - Thinking about adding an example using gcloud to pass the auth token. And clean up some duplicated examples that already present in the `-h` output.

**Comment by sethvargo** [comment]
I think I would prefer to just provide a single example in the README and then ask users to run `jvsctl token -h` for more examples. That ensures the example is versioned with the binary.

**Comment by yolocs** [comment]
Close per clean up in https://github.com/abcxyz/jvs/pull/213
