### ISSUE TITLE
Add simple prober to monitoring

### ISSUE THREAD

**Issue by yolocs** [abcxyz/jvs#221]
To continuously monitor JVS liveness, we need a basic prober. The basic logic is:

0. Give a JVS API endpoint
1. Request a token
2. Validate the token
3. Write a success metric data point
4. Repeat after a while

We then set up alerting based on the success metric.

We already have `jvsctl` that's capable of requesting/validating token. We can build an image on top of it.
We can use [log-based metrics](https://cloud.google.com/logging/docs/logs-based-metrics).
We can use cloud scheduler for the repeat.

**Comment by yolocs** [comment]
Can we close this now? @sailorlqh

**Comment by sailorlqh** [comment]
> Can we close this now? @sailorlqh

I will close this once #243 is merged. @yolocs

**Comment by sailorlqh** [comment]
Fixed by #243
