### ISSUE TITLE
Modify State Storage to use firestore instead of labels

### ISSUE THREAD

**Issue by raserva** [abcxyz/jvs#26]
Seth raised a few concerns with using labels to store state info:

- We're creating an implicit contract that our system, and only our system, manages that key
- We have tight control over our database; we dont have complete control over who can modify key labels
    - GCP resource hierarchy
    - someone with project-owner or higher permissions on the folder or org could modify it
    - having something so critical (lifecycle) be stored in a user-mutatable location is a concern

We should modify it to use firestore.

**Comment by capri-xiyue** [comment]
We may not choose to use firestore. Close it for now.
