### ISSUE TITLE
Append Jira Issue Id and Link to Justification

### ISSUE THREAD

**Issue by qiaoweiz** [abcxyz/jvs#318]
**Background:** 

Identification for Jira Issue can be achieved using either the Jira Issue Id or Jira issue key. However, it is important to note that the Jira issue key is not stable and can change if the issue is moved to a different project. On the other hand, the Jira Issue Id remains stable, but acquiring it through the UI interface is challenging. As a solution, we plan to modify the Jira plugin interface to include the Jira Issue Id in the Justification. In addition to that, a clickable link will prove to be valuable as it allows auditors to jump directly to the relevant issue, streamlining the audit process and enhancing efficiency.

**Implementation Plan:**

- Step1: Adjust Plugin interface to allow return Jira Issue Id
  - Update ValidateJustificationResponse proto with a new field, annotation. This is to store additional info the plugin might want to encapsulate in the Justification. 
  - Update [abcxyz/jvs-plugin-jira](https://github.com/abcxyz/jvs-plugin-jira).
 - Step2: Append Jira Issue Id and Issue Clickable Link to Justification
 - Step3: Testing and update Lumberjack
 - Step4: Deploy to Plato

**Comment by yolocs** [comment]
Could you copy over the high level change we're proposing and why it will be useful? This will help preserve the context in this repo.

**Comment by sqin2019** [comment]
@qiaoweiz closing, feel free to reopen.
