### ISSUE TITLE
Bug: Add sane defaults for key rotation

### ISSUE THREAD

**Issue by raserva** [abcxyz/jvs#84]
The defaults set now are super low. 

https://github.com/abcxyz/jvs/blob/91bf5285819b5cf6809caa1712f4b89f2698b20a/terraform/modules/jvs-e2e/variables.tf#L42

These are intended for testing, and not for production evironments. We should determine sane defaults for the various rotation periods and set them as defaults.

**Comment by capri-xiyue** [comment]
It can be set by individual users. We don't have to change it in our modules.
